[build]
  command = "npm run build"
  publish = "dist"

# (선택) 로컬 netlify dev 시 Vite 감지
[dev]
  framework = "vite"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10" 
# SPA 라우팅: 새로고침/직접 접근 404 방지
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
